### ISSUE TITLE
Is this workshop public?

### ISSUE THREAD

**Issue by bogdanpetru** [r31gN/tdd-react-enzyme#1]
Hey, 

A workshop in TDD in react, sounds very good.
I would like to participate, Is this a public workshop? :)

**Comment by r31gN** [comment]
Hey :).

Actually, this workshop will be part of a public event that we will host this autumn (October) in Cluj. We will have invited speakers and GDEs and the event will focus on React/Angular (multiple workshops to chose from, presentations and an open discussion panel). 

Glad to hear interest from you. The event will have nominal invitations, but I'll keep an eye on your interest :D.

Also, I'll be doing a presentation in Timisoara next month based on an excerpt from this workshop. I don't see why I couldn't do that on a Cluj Javascripters meeting as well :)

**Comment by bogdanpetru** [comment]
Cool, thank you! I am doing a lot of react development, but I don't do testing and I feel the need to.
Would be great to participate! :)

**Comment by bogdanpetru** [comment]
I've just got an invitation to *Let’s Speak Javascript*.
Thank you! :)
